## See https://github.com/jekyll/minima/blob/master/_config_theme-dev.yml for configuration
title: Janardhan Sharma's Blog
author:
  name: jsharmadomain
description: >
  This blog hosts my writings on all things I do.
theme: minima
plugins:
  - jekyll-feed

sass:
  quiet_deps: true
  silence_deprecations: [import]

minima:
  skin: classic

  nav_pages:
    - avout.md

  show_excerpts: true

  social_links:
    - title: Source
      icon: github
      url: "https://github.com/jsharmadomain/janardhansharma.com"
